project:
  type: website
  output-dir: docs

website:
#  title: "Fish-MIP"
  image: "one_line_colour_logo.png"
  favicon: FishMIP_assets/one line logo/pngs/one-line-colour-logo_transparent_background.png
  navbar:
    background: primary
    logo: "one_line_colour_logo.png"
    logo-alt: FishMIP
    logo-href: /index.html
    collapse-below: lg
    right:
      - href: index.qmd
        text: Home
      - text: Approach
        href: about.qmd
      - text: People
        menu: 
          - text: Science Coordination Group
            href: sciencegroup.qmd
          - text: Modelling Teams
            href: modellingteams.qmd
          - text: Working Groups
            href: workinggroups.qmd
     # - text: Models
     #   menu: 
     #     - text: Global
     #       href: globalmodels.qmd
     #     - text: Regional
     #       href: regionalmodels.qmd
        #file: models.qmd
      - text: Protocols
        href: protocols.qmd
      - text: Publications
        href: publications.qmd
      - text: Data & Tools
        href: tools.qmd 
      #  menu: 
       #    - text: Outputs
        #     href: outputs.qmd
         #  - text: Tools
          #   href: tools.qmd
        #menu:
        #  - text: Input Explorer 
        #    href: datatools/interactivetool.qmd
        #  - text: Country level outputs
        #    href: datatools/inputexplorer.qmd
         # - text: Tutorials
          #  href: datatools/tutorials.qmd
        #  - text: Terms of Use
          #  href: datatools/termsofuse.qmd
        #href: tools.qmd
      - text: News
        menu: 
          - text: Events
            href: events.qmd
          - text: Blog
            href: blogs.qmd
      - text: Join us
        href: joinus.qmd
      - icon: twitter
        href: https://twitter.com/fishmip
        target: _blank
      - icon: github
        href: https://github.com/Fish-MIP
        target: _blank
  page-footer:
      background: "#9FD0D7" 
      left: "Copyright &copy; 2023 [Fish-MIP](https://github.com/Fish-MIP)"
      center: "Built using [Quarto](https://quarto.org/)"
      right: "<img src='FishMIP_assets/UN_OceanDecadeLogo.png' alt='UN Ocean Decade Logo' style='height: 7.5em; vertical-align: middle;'>"
format:
  html:
    theme: custom.scss
    #css: styles.css
    toc: false
    editor: visual
    